apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: development
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: mynginx1
    image: nginx:1.14.2
    ports:
    - containerPort: 80