{{- if and (eq .Values.resultConnectionStringSecret.create true) (eq .Values.dbConfig.credentials.useExistingSecret false)}}
{{with .Values.dbConfig}}
# --------------Secret Env Variable with the Connection String
apiVersion: v1
kind: Secret
metadata:
  name:  {{ $.Release.Name }}-{{ $.Chart.Name }}-cn-string-cfg
type: Opaque
stringData:
   pgSqlConnectionString: Host={{ $.Release.Name }}-{{ $.Chart.Name }}-db-rset-0.{{ $.Release.Name }}-{{ $.Chart.Name }}-db-svc;Port={{.port}};Database={{.defaultDbName}};Username={{.credentials.adminUser}};Password={{.credentials.adminPassword}};Pooling=true;Minimum Pool Size=0;Maximum Pool Size=100;Connection Lifetime=0;
{{- end }}
{{- end }}