#------------------------------------Database Credentials------------------------
{{- if eq .Values.dbConfig.credentials.useExistingSecret false}}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-{{ .Chart.Name }}-pg-cred-secret
  labels:
    {{- include "database.commonLabels" . | nindent 4}}    
type: Opaque
stringData:
  POSTGRES_USER: {{- .Values.dbConfig.credentials.adminUser}}
  POSTGRES_PASSWORD: {{- .Values.dbConfig.credentials.adminPassword}}
{{- end -}}