# --------------Secret Env Variable with the Connection String
apiVersion: v1
kind: Secret
metadata:
  name: api-job-sql-secret
type: Opaque
stringData:
   pgSqlConnectionString: Host=data-base-service;Port=5432;Database=postgres;User ID=postgres;Password=PataDeCabra@2020;Pooling=true;Minimum Pool Size=0;Maximum Pool Size=100;Connection Lifetime=0;


# --------------Role and Role Binding to allow the Init Container to see if database is already migrate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-reader
  namespace: default 
rules:
  - apiGroups: ["batch"] 
    resources: ["jobs"] 
    verbs: ["get", "list"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-reader-binding
  namespace: default 
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-reader 

---
# --------------Deployement and Service Itself
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-backends-deployment
  labels:
    app: students-service
    type: backend
    subtype: api
spec:
  replicas: 2
  selector:
    matchLabels:
      service-name: students-api
  template:
    metadata:
      labels:
        app: students-service
        type: backend
        subtype: api
        service-name: students-api
    spec:
      initContainers:
      - name: "students-api-init"
        image: "groundnuty/k8s-wait-for:1.3"
        imagePullPolicy: Always
        args: 
        - "job"
        - "students-database-migrator-job"
      containers:
      - name: backend-api
        image: host.minikube.internal:5000/students-api:v1.4
        imagePullPolicy: Always
        resources:
          limits:
             cpu: 220m
             memory: 275Mi
          requests:
            cpu: 200m
            memory: 256Mi 
        startupProbe:
          httpGet:
            path: /health/startup
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          successThreshold: 3
        ports:
        - containerPort: 8080
        env:
        - name: applicationUrl
          value: "http://localhost:8080"
        - name: ConnectionStrings__PgSql
          valueFrom:
            secretKeyRef:
               name: api-job-sql-secret
               key: pgSqlConnectionString
---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    service-name: students-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
