apiVersion: v1
kind: Secret
metadata:
  name: migration-job-sql-secret
type: Opaque
stringData:
   pgSqlConnectionString: Host=students-pg-master-sset-0.students-pg-master-svc;Port=5432;Database=studentsdb;Username=studentApiAdmin;Password=PataDeCabra@2020;Pooling=true;Minimum Pool Size=0;Maximum Pool Size=100;Connection Lifetime=0;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: students-database-migrator-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  ttlSecondsAfterFinished: 300
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: students-database-migrator
        imagePullPolicy: Always
        image: host.minikube.internal:5000/students-db-migrator:v1.4
        resources:
          limits:
             cpu: 220m
             memory: 275Mi
          requests:
            cpu: 200m
            memory: 256Mi
        env:
         - name: ConnectionStrings__PgSql
           valueFrom:
              secretKeyRef:
                name: migration-job-sql-secret
                key: pgSqlConnectionString
      restartPolicy: OnFailure
