apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-base-deployment
  labels:
    app: students-service
    type: db
spec:
  replicas: 1
  selector:
    matchLabels:
      dbName: students-db
  template:
    metadata:
      labels:
        app: students-service
        type: db
        dbName: students-db
    spec:
      containers:
      - name: pg-sql-server
        image: postgres:15.0
        resources:
          limits:
             cpu: 550m
             memory: 1100Mi
          requests:
            cpu: 500m
            memory: 1Gi            
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "PataDeCabra@2020"


---

apiVersion: v1
kind: Service
metadata:
  name: data-base-service
spec:
  type: ClusterIP
  selector:
    dbName: students-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
