apiVersion: v1
kind: Secret
metadata:
  name: migration-job-sql-secret
type: Opaque
stringData:
  sqlServerConnectionString: Server=data-base-service;Database=StudentsDb_Tests;User Id=sa;Password=PataDeCabra@2020;TrustServerCertificate=True;

---
apiVersion: batch/v1
kind: Job
metadata:
  name: students-database-migrator-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  ttlSecondsAfterFinished: 300
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: students-database-migrator
        image: host.minikube.internal:5000/students-db-migrator:v1.3
        resources:
          limits:
             cpu: 220m
             memory: 275Mi
          requests:
            cpu: 200m
            memory: 256Mi
        env:
         - name: ConnectionStrings__SqlServer
           valueFrom:
              secretKeyRef:
                name: migration-job-sql-secret
                key: sqlServerConnectionString
      restartPolicy: OnFailure
