# Use this if you want to deploy only one Database without replica. Config maps in backend and migrator needs to be updated

#------------------------------------Database Password------------------------
apiVersion: v1
kind: Secret
metadata:
  name:  students-pg-secret
  labels:
    app: students-api
    type: data-base
type: Opaque
stringData:
  POSTGRES_USER: studentApiAdmin
  POSTGRES_PASSWORD: PataDeCabra@2020
  POSTGRES_DB: studentsdb

---


#------------------------------------Statefult Set Of Database------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: students-pg-sset
spec:
  serviceName: "students-pg-svc"
  replicas: 1
  selector:
    matchLabels:
        app: students-api
        type: data-base
        sub-type: infra-db
  template:
    metadata:
      labels:
        app: students-api
        type: data-base
        sub-type: infra-db
    spec:
      containers:
      - name: pd-db
        image: postgres:15 
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: students-pg-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: students-pg-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: students-pg-secret
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi

---

#------------------------------------Headless Service------------------------

apiVersion: v1
kind: Service
metadata:
  name: students-pg-svc
  labels:
    app: students-api
    type: data-base
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: students-api
    type: data-base
    sub-type: infra-db
