image:
  repositoryUrl: host.minikube.internal:5000
  repositoryName: students-api
  tag: v1.4
  pullPolicy: Always

replicaCount: 2
resources:
  limits:
    cpu: 220m
    memory: 275Mi
  requests:
    cpu: 200m
    memory: 256Mi


probes:
  startup:
    path: /health/startup
    port: 8080
    failureThreshold: 30
    periodSeconds: 10
  liveness:
    path: /healthz
    port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    path: /ready
    port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
    successThreshold: 3

ports:
  deployment: 8080
  service: 8080

migrationJob:
  # Will Create a Init Container waiting for the release Job
  waitForMigrationJob: true
  # When  waitForMigrationJob and deployMigrationJobRbac are true it will deploy a new RBAC Role so that wait for container can connect to Kubectl api 
  deployMigrationJobRbac: true
  migrationJobName: 'students-db-migrator-studends-database-migrator--dbmgr-job'


databaseConnectionStringManagement:
  #Disable this Section entirely
  inject: true 
  existingSecretName: 'students-db-students-database-cn-string-cfg'


#For Canary Releases:
canaryReleases:
  canaryUpgradeRelease: false
  existingServiceName: students-bff-studends-backend-bff-svc

#If this is true the endpoint will override the name (simulate a new version):
mockNewVersion: false

#If this is true the endpoint will fail randomly by the given rate (simulate a new failure):
mockFailures:
  enabled: false
  rate: 0
