image:
  repositoryUrl: host.minikube.internal:5000
  repositoryName: students-api
  tag: v1.4
  pullPolicy: Always

replicaCount: 2
resources:
  limits:
    cpu: 220m
    memory: 275Mi
  requests:
    cpu: 200m
    memory: 256Mi


probes:
  startup:
    path: /health/startup
    port: 8080
    failureThreshold: 30
    periodSeconds: 10
  liveness:
    path: /healthz
    port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
    timeoutSeconds: 2
    failureThreshold: 3
  readiness:
    path: /ready
    port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
    successThreshold: 3

ports:
  deployment: 8080
  service: 8080

migrationJob:
  # Will Create a Init Container waiting for the release Job
  waitForMigrationJob: true
  # When  waitForMigrationJob and deployMigrationJobRbac are true it will deploy a new RBAC Role so that wait for container can connect to Kubectl api 
  deployMigrationJobRbac: true


databaseConnectionStringManagement:
  #Disable this Section entirely
  inject: true 
  createSecret: true
  #Settings when create settings is true:
  databaseServiceName: 'students-pg-master-sset-0.students-pg-master-svc'
  databasePort: 5432
  databaseName: studentsdb
  databaseUserName: 'studentApiAdmin'
  databasePassword: 'PataDeCabra@2020'

  #Only relevant when createSecret=false
  existingSecretName: ''
