version: '3.8'

services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - ./registry/htpasswd:/auth/htpasswd
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd