#For now only Master is supported
role: Master

image:
  repositoryUrl: docker.io
  repositoryName: postgres
  tag: 15
  pullPolicy: IfNotPresent

probes:
  startup:
    initialDelaySeconds: 0
    periodSeconds: 5
    failureThreshold: 30
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10

dbConfig:
  port: 5432
  defaultDbName: studentsdb
  credentials:
    useExistingSecret: false
    #When use existing secret is true:
    existingSecretName: ''
    #When use existing secret is false:
    adminUser: studentApiAdmin
    adminPassword: PataDeCabra@2020
  replication:
    replicationUserPassword: PataDeCabra@2020
  
resultConnectionStringSecret:
 #This section only works when dbConfig.credentials.useExistingSecret is false:
  create: true