# --------------Role and Role Binding to allow the Init Container to see if database is already migrate
{{- if (eq .Values.canaryReleases.canaryUpgradeRelease false)}}
{{- if  and (eq .Values.migrationJob.waitForMigrationJob true) (eq .Values.migrationJob.deployMigrationJobRbac true)}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  {{ .Release.Name }}-{{ .Chart.Name }}-job-reader-role
  namespace: default 
rules:
  - apiGroups: ["batch"] 
    resources: ["jobs"] 
    verbs: ["get", "list"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ .Release.Name }}-{{ .Chart.Name }}-job-reader-role-binding
  namespace: default 
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-{{ .Chart.Name }}-job-reader-role
  {{- end -}}
  {{- end -}}