{{- if (eq .Values.canaryReleases.canaryUpgradeRelease false)}}
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}-{{ .Chart.Name }}-svc
  labels:
    {{- include "backend.commonLabels" . | nindent 4}}
spec:
  type: ClusterIP
  selector:
     {{- include "backend.matchLabels" . | nindent 6}}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.service }}
      targetPort: {{ .Values.ports.deployment }}
{{- end }}