{{with .Values.databaseConnectionStringManagement}}
{{- if  and (eq .inject true) (eq .createSecret true)}}
# --------------Secret Env Variable with the Connection String
apiVersion: v1
kind: Secret
metadata:
  name:  {{ $.Release.Name }}-{{ $.Chart.Name }}-migrator-cfg
type: Opaque
stringData:
   pgSqlConnectionString: Host={{.databaseServiceName}};Port={{.databasePort}};Database={{.databaseName}};Username={{.databaseUserName}};Password={{.databasePassword}};Pooling=true;Minimum Pool Size=0;Maximum Pool Size=100;Connection Lifetime=0;
{{- end }}
{{- end }}