{{- /* 
  This is a multiline GO Lang comment and wont be rendered in the output
*/ -}}


# This is a YAML Comment and will be rendered in the output
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:    
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      #Here is how to use Global Variables
      chartType: {{ .Values.global.subchartType }}
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: nginx
        image: '1.27.3'
        ports:
        - containerPort: 80

