apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pedrito-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pedrito-role-binding
  namespace: default
subjects:
- kind: Group
  name: developer 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pedrito-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15
        ports:
        - containerPort: 80
