{{- if and (eq .Values.backends.studentsApi.inject true) (eq .Values.backends.studentsApi.injectFromExistingSecret false)}}
{{with .Values.backends.studentsApi}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ $.Chart.Name }}-be-api-details
data:
  Backends__StudentsApi: "{{.backendSchema}}://{{.backendServiceName}}:{{.backendPort}}"
{{- end }}
{{- end }}

