{{- /* Validations are a good practice to use a validation file or normally add them at the top of the file itself */ -}}
{{- /* Validations dont work directly from a _xxx.tpl file unless they are part of the function */ -}}

# Validation Using fail function

{{- if not .Values.validationObject.myRequiredProperty }}
  {{ fail "validationObject.myRequiredProperty is missing! Update values.yaml" }}
{{- end }}

# Validation using required function
{{- $_ := required "validationObject.anotherRequiredProperty is missing! Update values.yaml" .Values.validationObject.anotherRequiredProperty  }}