apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-new-pv
  labels: 
    volume-type: ssd
    aws-availability-zone: us-east-1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  my-new-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      volume-type: ssd
      aws-availability-zone: us-east-1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName:  my-new-pvc
      containers:
      - name: nginx
        image: nginx:1.15
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: task-pv-storage
        ports:
        - containerPort: 80
     