#For a Pod that defines an emptyDir volume, the volume is created when the Pod is assigned to a node.
#As the name says, the emptyDir volume is initially empty. 
#All containers in the Pod can read and write the same files in the emptyDir volume,
#though that volume can be mounted at the same or different paths in each container.
#When a Pod is removed from a node for any reason, the data in the emptyDir is deleted permanently.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15
        volumeMounts:
          - mountPath: /cache
            name: cache-volume
        ports:
        - containerPort: 80
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 500Mi

