apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: mynginx1
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: mynginx2
    image: nginx:1.14.2
    ports:
    - containerPort: 80
