apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  completions: 3          # Number of successful completions needed
  parallelism: 2          # Number of pods running in parallel
  backoffLimit: 4         # Number of retries before considering the job failed
  ttlSecondsAfterFinished: 10 # Pods Will bne removed after this time
  activeDeadlineSeconds: 100 # Once a Job reaches activeDeadlineSeconds, all of its running Pods are terminated and the Job status will become type: Failed with reason: DeadlineExceeded.
  template:
    spec:
      containers:
      - name: example
        image: busybox
        command: ["sh", "-c", "echo 'Running...'; sleep 20"]
      restartPolicy: OnFailure #Only OnFailure and Never ar valid