#This example creates a CronJob that runs every minute to print a message (Hello, Kubernetes!) to the logs and waits for 20 seconds.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/1 * * * *" # Runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example
            image: busybox
            command: ["sh", "-c", "echo 'Hello, Kubernetes!'; sleep 20"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3  # Keep 3 successful jobs
  failedJobsHistoryLimit: 1      # Keep 1 failed job