apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-job
  annotations:
    # A Hook normally is a Kubernetes resourced deployed only when an event happen. It should only be used to create one-off resources like jobs
    # Only when this Event Happens
    "helm.sh/hook": pre-install
    # When the item should be deleted
    "helm.sh/hook-delete-policy": hook-succeeded
    # In case there are multiple hooks for the same event they will be executed in increased order
    x"helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      containers:
        - name: init
          image: busybox
          command: ["echo", "Running pre-install job"]
      restartPolicy: Never